apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: apache
  name: apache
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apache
  template:
    metadata:
      labels:
        app: apache
    spec:
      containers:
        - image: httpd:2.4.58
          name: apache
          ports:
          - containerPort: 8080
          resources:
            limits:
              cpu: 1
              memory: 512Mi
              ephemeral-storage: 1Gi
            requests:
              cpu: "0.5"
              memory: 256Mi
              ephemeral-storage: 1Gi
--- 
